### ISSUE TITLE
Ability to trigger GC of a bookie using the HTTP REST API

### ISSUE THREAD

**Issue by eolivelli** [diennea/bookkeeper-visual-manager#103]
**FEATURE REQUEST**

in BKVM 3.0 we can know the http address of the Bookie (in "endpoints" variable).
Knowing the http address enables us to use the HTTP REST API of the Bookie, and in particular the "trigger gc" API, that tells to the bookie to execute the GC (Garbage collection) as soon as possible.

https://bookkeeper.apache.org/docs/latest/admin/http/#endpoint-apiv1bookiegc

We can add a button on the Bookie Card that opens dialog and then after user confirmation calls the trigger gc API.
In the dialog we can show the GC status of the Bookie (using the GET method of bookie gc API)
We could also show other interesting information about the Bookie using the API

This is the first activity that operates on the cluster, probably we need a configuration flag to enable it.

In the future it will be also good to have a "role" for users: users with read-only access and users with write/ops permissions

**Comment by aluccaroni** [comment]
+1 on flag and/or role to abilitate this feature (since can be prone to abuse)

**Comment by aluccaroni** [comment]
Fixed in https://github.com/diennea/bookkeeper-visual-manager/pull/118
