### ISSUE TITLE
[BUG] Error Age time on dashboard

### ISSUE THREAD

**Issue by liangyuanpeng** [diennea/bookkeeper-visual-manager#112]
**BUG REPORT**

1. Please describe the issue you observed:  

Error Age time on dashboard

- What did you do?

- What did you expect to see?

- What did you see instead?    

Age of Detail info is correct.

![image](https://user-images.githubusercontent.com/28711504/123051576-8504bc00-d434-11eb-9276-6dc89826881d.png)

**Comment by hamadodene** [comment]
Thanks @liangyuanpeng , the fix will be integrate in the next release
