### ISSUE TITLE
Provide docker image for simple deployment

### ISSUE THREAD

**Issue by truong-hua** [diennea/bookkeeper-visual-manager#116]
**FEATURE REQUEST**

It's easier for any one if we can provide a public pre-built docker image on dockerhub.com which is configurable through environment variables.

Just one command line with `docker run` will allow any one to experiment this product easily.

**Comment by eolivelli** [comment]
good idea !

**Comment by eolivelli** [comment]
@truong-hua would you have time to contribute a patch ?

**Comment by aluccaroni** [comment]
Fixed with https://github.com/diennea/bookkeeper-visual-manager/pull/122
