### ISSUE TITLE
Upgrade to Bookkeeper 4.10

### ISSUE THREAD

**Issue by mino181295** [diennea/bookkeeper-visual-manager#15]
When will Bookkeeper 4.10 be released:

- Zookeeper connection should be removed to avoid extra configuration
- Provide only metadataServiceUri to the application

**Comment by eolivelli** [comment]
@mino181295  BookKeeper 4.10.0 has been released to Maven Central.
You can finalize this task now,
Hopefully we can have a release within Chrismas
