### ISSUE TITLE
Add Global cluster configuration view

### ISSUE THREAD

**Issue by eolivelli** [diennea/bookkeeper-visual-manager#20]
It would be useful to have a page with global information about the local client configuration (the configuration used to boot the client)

**Comment by aluccaroni** [comment]
Also we should add information about shared configuration such as the current layout, default config of BK, automatic re-replication status, Auditor status, etc

**Comment by eolivelli** [comment]
fixed with ded8f9573bc56a7c27a6e74fe205382d6426d3ba
