### ISSUE TITLE
Bookies page - Add markdown to the Bookies status

### ISSUE THREAD

**Issue by aluccaroni** [diennea/bookkeeper-visual-manager#26]
Under the Bookies page (the Home) it could be usefulto have different backfground color for the Bookies "boxes" based on the service status.

For example:
- Blue for UP
- Light Gray for READONLY
- Dark Gray for DOWN

(or the usual green/red/yellow...but with the current graphics maybe better to stick to blue/green colours)

**Comment by eolivelli** [comment]
This has been partially fixed by ded8f9573bc56a7c27a6e74fe205382d6426d3ba

Now we have the state of the bookie: available/readonly/down

but without colours

**Comment by aluccaroni** [comment]
This should be fixed by https://github.com/diennea/bookkeeper-visual-manager/pull/54, but the result of the pull  is not very usable:

- the "Bookie cards" can be very big (on a 1440x900 monitor i can see barely 2 rows of bookies)
- the cards width is dependent on the bookie name:port OR on the status (with ~36 char lenght bookie name on the same monitor as above i can see only 2 bookie card on one line)

I think a fixed width and a general scale down of the cards is in order to render the page more usable. 

If possible the cards should automagially scale down to fit the screen (this pose new problems, since you should change the amount of info inside the card based on the screen size and number of bookies...at the very minimum you should see only a truncated name, the status and the % usage). I strongly support this last implementation, it's very important however that all the cards needs to be of the same dimension.

**Comment by eolivelli** [comment]
@dcdiennea PTAL

**Comment by aluccaroni** [comment]
last issue addressed in https://github.com/diennea/bookkeeper-visual-manager/pull/59
