### ISSUE TITLE
Ledger view - add search/filter advanced capability

### ISSUE THREAD

**Issue by aluccaroni** [diennea/bookkeeper-visual-manager#29]
It could be useful to be able to filter Ledger based on the metadata content. A typical example is a Bookie cluster used by different application (eg. pulsar and majordodo). An other exampole is filtering for OPEN/CLOSED ledger

**Comment by eolivelli** [comment]
This has been partially implemented.
Now we have to make in nicer.

**Comment by aluccaroni** [comment]
Since https://github.com/diennea/bookkeeper-visual-manager/pull/33 we are able to search in the custom metadata of ledgers.

Extend this capability to:
- search inside the default metadata (such as CLOSED/OPEN)
- filter upon which field to perform the search (eg. "State:"OPEN should search for "OPEN" only inside the "State" Metadata)
- enable multiple search with AND/OR/NOT operand

**Comment by eolivelli** [comment]
We have now a more advanced search:
- metadata
- ledger "age"
- range of ledger size

I feel that for the first release this is enough for inspecting a production cluster and see:
- resources used by a tenant
- resources used by an application
- discover orphan ledgers (with very long age)
- discover huge ledgers

Looking for OPEN/CLOSE state of a ledger is not very useful while inspecting a production cluster, maybe it can be useful to see if any ledgers has never been closed and so it is no a good candidate for re-replication, but actually we are not using re-replication
