### ISSUE TITLE
Ledger View - Provide sum of size of selected ledgers 

### ISSUE THREAD

**Issue by eolivelli** [diennea/bookkeeper-visual-manager#37]
Show in the main ledgers search page the sum of the sizes of the listed ledgers in a new fixed info box on the right.

This is important to see how much disk space is used by the given search, for instance a BlobIt bucket or a Pulsar topic

By default (no search) show the sum of all ledgers

**Comment by aluccaroni** [comment]
Resolved in https://github.com/diennea/bookkeeper-visual-manager/pull/99
