### ISSUE TITLE
Cache status UI Improvements

### ISSUE THREAD

**Issue by aluccaroni** [diennea/bookkeeper-visual-manager#41]
Improve Cache UI by:

- adding a refresh button to the cache page
- adding on the top right of the menu the time of the last refresh
- adding on the top right of the menu a refresh button

**Comment by eolivelli** [comment]
the first item "adding a refresh button to the cache page"  as been committed to master

**Comment by eolivelli** [comment]
we should report in every page the status of the cache:
- last update
- current status

**Comment by eolivelli** [comment]
done in 1.0
