### ISSUE TITLE
Create a first awesome UI using Vuetify

### ISSUE THREAD

**Issue by eolivelli** [diennea/bookkeeper-visual-manager#46]
- Create a first awesome UI Layout
- Use tables to show Bookies and Ledgers ?
- Move the menu bar on the left

**Comment by eolivelli** [comment]
@mino181295 this is your current work isn't it ?

**Comment by mino181295** [comment]
Yes, I'm currently working on PR https://github.com/diennea/bookkeeper-visual-manager/pull/47
