### ISSUE TITLE
Deploy on maven central

### ISSUE THREAD

**Issue by aluccaroni** [diennea/bookkeeper-visual-manager#69]
Deploy BKVM on maven central to ease deployment on downstream application

See also https://github.com/apache/pulsar-manager/issues/291

**Comment by eolivelli** [comment]
We should use a better name, like bkvm.org and buy the DNS name.

**Comment by eolivelli** [comment]
@sijie @tuteng PTAL

**Comment by aluccaroni** [comment]
Done https://search.maven.org/search?q=org.bkvm
