### ISSUE TITLE
Build Initial Configuration setup

### ISSUE THREAD

**Issue by mino181295** [diennea/bookkeeper-visual-manager#7]
In this issue I want to provide an easy, modular way to provide to the _.war_ application a initial static configuration.

My idea is to have 2 ways to provide the configuation:
- Simple : have just one parameter to the serviceMetadataUri for simple configurations. Plug and play mode useful for testing and easy setups.
- Advanced.

In the advanced a Properties configuration loaded by a file path provided via:
- System Property (bad in big systems where you can't restart the server)
- Environment variable
- web.xml (bad because you have to recompile or override it)

It would also be nice to read directly a bookkeeper configuration file

**Comment by mino181295** [comment]
What do you think @eolivelli

**Comment by eolivelli** [comment]
Sounds good
