### ISSUE TITLE
Support Multiple clusters

### ISSUE THREAD

**Issue by eolivelli** [diennea/bookkeeper-visual-manager#72]
As Apache Pulsar Manager supports multiple environments (Pulsar Cluster) it is better to implement the ability to connect to multiple clusters.

We can create multiple BK clients, and add a "idcluster" on every table on database.
the only aspect that we can't deal with is JAAS authentication as it is handle at Jave Runtime level.

**Comment by eolivelli** [comment]
@sijie @tuteng PTAL

**Comment by tuteng** [comment]
LGTM
